System.Boolean:
  align: Left
  width: 25mm
System.Byte:
  align: Left
  width: 25mm
System.Char:
  align: Left
  width: 25mm
System.DateTime:
  align: Left
  format: dd/MM/yyyy
  width: 20mm
System.Decimal:
  align: Right
  format: N2
  overrides:
    exchangerate:
      format: N4
    kur:
      format: N4
  width: 25mm
System.Double:
  align: Right
  format: N2
  width: 25mm
System.Guid:
  align: Left
  width: 25mm
System.Int16:
  align: Left
  width: 25mm
System.Int32:
  align: Left
  width: 25mm
System.Int64:
  align: Left
  width: 25mm
System.Object:
  align: Left
  width: 25mm
System.SByte:
  align: Left
  width: 25mm
System.Single:
  align: Left
  width: 25mm
System.String:
  align: Left
  format: null
  overrides:
    currencycode:
      width: 12mm
    description:
      width: 75mm
    firstlastname:
      width: 40mm
    parabiri:
      width: 12mm
    storecode:
      width: 15mm
    typecode:
      width: 15mm
  width: 25mm
